### ISSUE TITLE
Consider removing pino

### ISSUE THREAD

**Issue by smebberson** [allanchau/node-http-error#52]
I think adding pino has over-broadened what node-http-error does, and I think it's a little too opinionated. I think logging should happen alongside node-http-error, not inside node-http-error.

**Comment by smebberson** [comment]
You could create another module called `node-http-error-log`, which could support the same object construct as this module, but sit just before this one in the middleware chain, and could use pino to log?

**Comment by smebberson** [comment]
You could update this to be a monorepo with those two modules, or you could export the middleware like `const httpErrorLog = require('allanchau-http-error/log');`?

**Comment by smebberson** [comment]
Actually, the recent rewrite makes this module less flexible and means you can't really support the two ideas above...

**Comment by allanchau** [comment]
@smebberson I've removed it now and also added the ability to provide some defaults.
